const ADD = 'ADD'
const DELETE = 'DELETE'
const UPDATE = 'UPDATE'
const SELECTED = 'SELECTED'
const DELETE_SELECTED = 'DELETE_SELECTED'
const DONE_SELECTED = 'DONE_SELECTED'
const DONE = 'DONE'
const SELECTED_ALL = 'SELECTED_ALL'
const SET_FILTER = 'SET_FILTER'
const SET_FILTER_PRODUCT = 'SET_FILTER_PRODUCT'

export {ADD, UPDATE, DELETE, SELECTED, SELECTED_ALL, DONE, DELETE_SELECTED, DONE_SELECTED, SET_FILTER, SET_FILTER_PRODUCT}